import { Product } from "./types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name_kr: "비비고 베트남 쌀국수 & 칠리소스 기획 세트",
    name_vn: "Bộ gia vị Phở & Nước tương ớt Bibigo (Kèm sốt)",
    category: "🇻🇳 베트남 식자재/생필품",
    coupang_price: 18900,
    coupang_link: "https://link.coupang.com/a/example_pho_set",
    is_rocket: true,
    naver_price: 17900,
    naver_link: "https://smartstore.naver.com/example/products/pho_set",
    naver_point_back: 500,
    original_price: 24000,
    discount_rate: 21,
    lowest_price_30days: 17500,
    price_history_trend: "🔥 지난달 대비 21% 할인 (네이버 최저가)",
    image_url: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=600&auto=format&fit=crop&q=80",
    badge: "베트남 인기 1위",
    rating: 4.9,
    review_count: 3240,
    features_kr: ["현지 스타일 진한 육수", "칠리소스 포함", "5분 간편 조리", "로켓배송 가능"],
    features_vn: ["Hương vị phở chuẩn vị", "Kèm nước tương ớt", "Nấu nhanh 5 phút", "Giao hỏa tốc"]
  },
  {
    id: "prod-2",
    name_kr: "정관장 홍삼정 에브리타임 뗏(Tết) 명절 선물세트",
    name_vn: "Hộp quà Tết Hồng sâm Cheong Kwan Jang Everytime",
    category: "🎁 기념일/뗏(Tết) 선물",
    coupang_price: 92000,
    coupang_link: "https://link.coupang.com/a/example_redginseng",
    is_rocket: true,
    naver_price: 95000,
    naver_link: "https://smartstore.naver.com/example/products/redginseng",
    naver_point_back: 2800,
    original_price: 102000,
    discount_rate: 10,
    lowest_price_30days: 91500,
    price_history_trend: "🔥 지난달 대비 10% 할인 (쿠팡 로켓 최저가)",
    image_url: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&auto=format&fit=crop&q=80",
    badge: "🎁 Tết 선물 추천",
    rating: 4.9,
    review_count: 12450,
    features_kr: ["100% 6년근 홍삼농축액", "스틱형 파우치", "고급 선물 포장", "쇼핑백 증정"],
    features_vn: ["100% Hồng sâm 6 năm", "Gói nước tiện lợi", "Đóng hộp sang trọng", "Tặng túi quà biếu"]
  },
  {
    id: "prod-3",
    name_kr: "설화수 자음 2종 수액/유액 기초 선물 세트",
    name_vn: "Bộ dưỡng da cao cấp Sulwhasoo Essential Duo",
    category: "💄 K-뷰티/건강",
    coupang_price: 115000,
    coupang_link: "https://link.coupang.com/a/example_sulwhasoo",
    is_rocket: true,
    naver_price: 112000,
    naver_link: "https://smartstore.naver.com/example/products/sulwhasoo",
    naver_point_back: 1500,
    original_price: 145000,
    discount_rate: 20,
    lowest_price_30days: 110000,
    price_history_trend: "🔥 최근 30일 내 가장 높은 할인률",
    image_url: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&auto=format&fit=crop&q=80",
    badge: "K-Beauty Best",
    rating: 4.8,
    review_count: 5310,
    features_kr: ["한방 보습 영양 케어", "자음수 + 자음유액 세트", "주름 개선 효과", "무료선물포장"],
    features_vn: ["Dưỡng ẩm Đông y", "Bộ nước hoa hồng & sữa dưỡng", "Chống lão hóa", "Bao gói biếu quà"]
  },
  {
    id: "prod-4",
    name_kr: "애플 에어팟 프로 2세대 USB-C",
    name_vn: "Tai nghe Bluetooth Apple AirPods Pro 2 USB-C",
    category: "家電 가전/디지털",
    coupang_price: 319000,
    coupang_link: "https://link.coupang.com/a/example_airpods",
    is_rocket: true,
    naver_price: 324000,
    naver_link: "https://smartstore.naver.com/example/products/airpods",
    naver_point_back: 5000,
    original_price: 359000,
    discount_rate: 11,
    lowest_price_30days: 315000,
    price_history_trend: "🔥 쿠팡 와우 로켓 최저가 혜택",
    image_url: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=600&auto=format&fit=crop&q=80",
    badge: "베스트셀러",
    rating: 4.9,
    review_count: 14820,
    features_kr: ["액티브 노이즈캔슬링", "최대 6시간 연속재생", "Apple H2 칩셋", "C타입 로켓배송"],
    features_vn: ["Chống ồn ANC", "Pin 6 giờ liên tục", "Chip Apple H2", "Cổng Type-C mới"]
  },
  {
    id: "prod-5",
    name_kr: "쿠쿠 6인용 IH 전기압력밥솥 (다국어 음성지원)",
    name_vn: "Nồi cơm điện cao tần Cuckoo 6 người (Có giọng nói)",
    category: "家電 가전/디지털",
    coupang_price: 248000,
    coupang_link: "https://link.coupang.com/a/example_cuckoo",
    is_rocket: true,
    naver_price: 245000,
    naver_link: "https://smartstore.naver.com/example/products/cuckoo",
    naver_point_back: 3500,
    original_price: 298000,
    discount_rate: 16,
    lowest_price_30days: 242000,
    price_history_trend: "🔥 지난주 대비 1.5만원 가격 하락",
    image_url: "https://images.unsplash.com/photo-1544233726-9f1d2b27be8b?w=600&auto=format&fit=crop&q=80",
    badge: "필수 가전",
    rating: 4.9,
    review_count: 8900,
    features_kr: ["고화력 IH 안남미 조리", "한국어/영문 음성지원", "스텐 내솥 위생관리", "자동 스팀 세척"],
    features_vn: ["Công nghệ IH dẻo cơm", "Hướng dẫn giọng nói", "Lòng nồi inox", "Tự động làm sạch"]
  },
  {
    id: "prod-6",
    name_kr: "코코넛 워터 100% 330ml x 24팩 대용량",
    name_vn: "Nước dừa tươi nguyên chất 100% (Thùng 24 hộp)",
    category: "🇻🇳 베트남 식자재/생필품",
    coupang_price: 22900,
    coupang_link: "https://link.coupang.com/a/example_coconut_water",
    is_rocket: true,
    naver_price: 21900,
    naver_link: "https://smartstore.naver.com/example/products/coconut_water",
    naver_point_back: 600,
    original_price: 28000,
    discount_rate: 18,
    lowest_price_30days: 21500,
    price_history_trend: "🔥 네이버 스마트스토어 최저가",
    image_url: "https://images.unsplash.com/photo-1525385133512-2f3bdd039054?w=600&auto=format&fit=crop&q=80",
    badge: "인기 음료",
    rating: 4.8,
    review_count: 2100,
    features_kr: ["100% 순수 코코넛", "무설탕 무첨가물", "빠른 전해질 보충", "무료배송"],
    features_vn: ["100% dừa tươi", "Không đường", "Bổ sung điện giải", "Miễn phí giao hàng"]
  }
];
